# Simplified Cloud Build configuration without secrets
# Use this if you prefer to set environment variables directly in Cloud Run
# For production, consider using cloudbuild.yaml with Secret Manager

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/linkchat-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/linkchat-backend:latest'
      - '.'
    dir: 'backend'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/linkchat-backend:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/linkchat-backend:latest'

  # Deploy container image to Cloud Run
  # Note: Environment variables should be set separately using:
  # gcloud run services update linkchat-backend --update-env-vars "KEY=VALUE"
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'linkchat-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/linkchat-backend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'PORT=8080,NODE_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/linkchat-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/linkchat-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

